config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'users#login'
  post 'signin', to: 'users#login'
  get 'register', to: 'users#register'
  post 'signup', to: 'users#signup'

  # resources :post
  resources :posts
  root to: 'posts#index' 
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def show

    end

    def new
        @post = Post.new
    end


    def index
        # @posts = User.find(2).posts
        @posts = Post.order(id: :desc)
    end

    def create

        # @post = Post.create(post_params)
        # @post.user_id = 2
        @post = User.find(2).posts.create(post_params)
        # @post.save

        if @post.id
            redirect_to :posts
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
       
       if @post.update(post_params)
        redirect_to action: :index
       else
        render :edit
       end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy!
        redirect_to :posts
    end


    private
        def post_params
            params.require(:post).permit(:title, :content)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end

  def signin
  end

  def register
  end

  def signup
    @user = User.create(name: params[:name], password: params[password], password_confirmation: params[password_confirmation])
    if @user.persisted?
      session[:id] = @user.id
      redirect_to :root
    else
      render :register
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="<%= root_path %>">Home</span></a>
        <a class="nav-item nav-link" href="<%= new_post_path %>">New</a>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <h1><%= head%></h1>

  <%= form_for(@post, url: @post) do |f| %>
    <div class="form-group">
      <%= f.text_field(:title, class: 'form-control')  %>
      <%= @post.errors.full_messages.first %>
    </div>

    <div class="form-group">
      <%= f.text_area(:content, class: 'form-control', rows: 5)%><br>
      <%= @post.errors.full_messages.second %>
    </div>

      <%= submit_tag btnt, class: "btn btn-#{btnc} col-md-12"  %>
    <% end %>

</div>

  

app/views/posts/edit.html.erb
<%= render partial: 'form', locals: {btnt: "Update", btnc: "info", head: "Update Post"} %>

app/views/posts/index.html.erb
<div class="container">
    <h1>Home</h1>
    <% @posts.each do |post| %>
        <div class="card md-12 mb-3">
            <div class="card-body">
                <h3 class="card-title"><%= post.title %></h3>
                <h7 class="card-title"><b><%= post.user.name %></b></h7>
                <p class="card-text"><%= post.content %></p>
                <a href="<%= edit_post_path(post.id) %>" class="btn btn-primary"> Update </a>
                <%= link_to 'Delete', post, method: :delete,  class: "btn btn-danger" %>
            </div>
        </div>  

    <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: 'form', locals: {btnt: "Post", btnc: "success", head: "New Post"} %>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/register.html.erb
<h1>Users#register</h1>
<p>Find me in app/views/users/register.html.erb</p>

<div class="container col-md-6">
    <%= form_tag( signup_path) do %>
        <div class="form-group">
        <%= text_field_tag :name, nil, class: 'form-control', placeholder: 'User Name'  %>
        </div>

        <div class="form-group">
        <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'Password'  %>
        </div>

        <div class="form-group">
        <%= password_field_tag :password_confirmation, nil, class: 'form-control', placeholder: 'Confirm Password'  %>
        </div>

        <%= submit_tag "SignUp", class: "btn btn-success col-md-12"  %>
        <% end %>
</div>